Retry to connect to MQTT broker on OSError
After a power outage, when the local router is not yet up, network with MQTT broker may fail with a timeout and/or OSError exceptions.
I see the following error in the log:
OSError: [Errno 113] No route to host
In such a case, we need to retry connecting to MQTT, just like we do for a timeout.